struct output_v  
{  
    float4 position:POSITION;  
    float3 color:COLOR;  
    float2 texCoord:TEXCOORD0;  
};  
  
output_v main_v(float2 position:POSITION,  
                        float3 color:COLOR,  
                        float2 texCoord:TEXCOORD0)  
{  
    output_v OUT;  
    OUT.position = float4(position,0,1);  
    OUT.color = color;  
    OUT.texCoord = texCoord;  
      
    return OUT;  
}  